/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    posts: Post;
    pages: Page;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL segment, e.g. tutorials
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  category?: (number | null) | Category;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use "home" for the homepage
   */
  slug: string;
  layout?:
    | (
        | HeroBlock
        | FeaturesBlock
        | ContentBlock
        | StepsBlock
        | StatsBlock
        | FaqsBlock
        | PricingBlock
        | TestimonialsBlock
        | BrandsBlock
        | CallToActionBlock
        | BlogLatestPostsBlock
        | NoteBlock
        | FormBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  variant?: ('centered' | 'split') | null;
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  actions?:
    | {
        variant?: ('primary' | 'secondary' | 'tertiary' | 'link') | null;
        text: string;
        href: string;
        /**
         * astro-icon name, e.g. tabler:rocket
         */
        icon?: string | null;
        target?: ('_self' | '_blank') | null;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock".
 */
export interface FeaturesBlock {
  variant?: ('grid' | 'twocol' | 'image') | null;
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  columns?: ('2' | '3') | null;
  image?: (number | null) | Media;
  items?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * astro-icon name
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  columns?: ('1' | '2') | null;
  items?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * astro-icon name
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  callToAction?: {
    variant?: ('primary' | 'secondary' | 'tertiary' | 'link') | null;
    text?: string | null;
    href?: string | null;
    icon?: string | null;
    target?: ('_self' | '_blank') | null;
  };
  isReversed?: boolean | null;
  isAfterContent?: boolean | null;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  variant?: ('timeline' | 'twocol') | null;
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  items?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * astro-icon name
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  callToAction?: {
    variant?: ('primary' | 'secondary' | 'tertiary' | 'link') | null;
    text?: string | null;
    href?: string | null;
    icon?: string | null;
    target?: ('_self' | '_blank') | null;
  };
  isReversed?: boolean | null;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  stats?:
    | {
        amount?: string | null;
        title?: string | null;
        description?: string | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqsBlock".
 */
export interface FaqsBlock {
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  columns?: ('1' | '2') | null;
  items?:
    | {
        title?: string | null;
        description?: string | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  prices?:
    | {
        title?: string | null;
        subtitle?: string | null;
        price?: string | null;
        period?: string | null;
        items?:
          | {
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        hasRibbon?: boolean | null;
        ribbonTitle?: string | null;
        callToAction?: {
          variant?: ('primary' | 'secondary' | 'tertiary' | 'link') | null;
          text?: string | null;
          href?: string | null;
          icon?: string | null;
          target?: ('_self' | '_blank') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  testimonials?:
    | {
        testimonial?: string | null;
        name?: string | null;
        job?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  callToAction?: {
    variant?: ('primary' | 'secondary' | 'tertiary' | 'link') | null;
    text?: string | null;
    href?: string | null;
    icon?: string | null;
    target?: ('_self' | '_blank') | null;
  };
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandsBlock".
 */
export interface BrandsBlock {
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'brands';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  actions?:
    | {
        variant?: ('primary' | 'secondary' | 'tertiary' | 'link') | null;
        text: string;
        href: string;
        /**
         * astro-icon name, e.g. tabler:rocket
         */
        icon?: string | null;
        target?: ('_self' | '_blank') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogLatestPostsBlock".
 */
export interface BlogLatestPostsBlock {
  title?: string | null;
  information?: string | null;
  count?: number | null;
  linkText?: string | null;
  linkUrl?: string | null;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogLatestPosts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NoteBlock".
 */
export interface NoteBlock {
  content?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'note';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  tagline?: string | null;
  title?: string | null;
  subtitle?: string | null;
  /**
   * Choose a form built with the Form Builder.
   */
  form: number | Form;
  /**
   * Optional #anchor id
   */
  anchorId?: string | null;
  isDark?: boolean | null;
  background?: ('default' | 'muted' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'posts';
        value: number | Post;
      };
  slug?: string | null;
  excerpt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        faqs?: T | FaqsBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        brands?: T | BrandsBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        blogLatestPosts?: T | BlogLatestPostsBlockSelect<T>;
        note?: T | NoteBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  tagline?: T;
  title?: T;
  subtitle?: T;
  content?: T;
  actions?:
    | T
    | {
        variant?: T;
        text?: T;
        href?: T;
        icon?: T;
        target?: T;
        id?: T;
      };
  image?: T;
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock_select".
 */
export interface FeaturesBlockSelect<T extends boolean = true> {
  variant?: T;
  tagline?: T;
  title?: T;
  subtitle?: T;
  columns?: T;
  image?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  tagline?: T;
  title?: T;
  subtitle?: T;
  content?: T;
  image?: T;
  columns?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  callToAction?:
    | T
    | {
        variant?: T;
        text?: T;
        href?: T;
        icon?: T;
        target?: T;
      };
  isReversed?: T;
  isAfterContent?: T;
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  variant?: T;
  tagline?: T;
  title?: T;
  subtitle?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  image?: T;
  callToAction?:
    | T
    | {
        variant?: T;
        text?: T;
        href?: T;
        icon?: T;
        target?: T;
      };
  isReversed?: T;
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  tagline?: T;
  title?: T;
  subtitle?: T;
  stats?:
    | T
    | {
        amount?: T;
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqsBlock_select".
 */
export interface FaqsBlockSelect<T extends boolean = true> {
  tagline?: T;
  title?: T;
  subtitle?: T;
  columns?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  tagline?: T;
  title?: T;
  subtitle?: T;
  prices?:
    | T
    | {
        title?: T;
        subtitle?: T;
        price?: T;
        period?: T;
        items?:
          | T
          | {
              description?: T;
              id?: T;
            };
        hasRibbon?: T;
        ribbonTitle?: T;
        callToAction?:
          | T
          | {
              variant?: T;
              text?: T;
              href?: T;
              icon?: T;
              target?: T;
            };
        id?: T;
      };
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  tagline?: T;
  title?: T;
  subtitle?: T;
  testimonials?:
    | T
    | {
        testimonial?: T;
        name?: T;
        job?: T;
        image?: T;
        id?: T;
      };
  callToAction?:
    | T
    | {
        variant?: T;
        text?: T;
        href?: T;
        icon?: T;
        target?: T;
      };
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandsBlock_select".
 */
export interface BrandsBlockSelect<T extends boolean = true> {
  tagline?: T;
  title?: T;
  subtitle?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  tagline?: T;
  title?: T;
  subtitle?: T;
  actions?:
    | T
    | {
        variant?: T;
        text?: T;
        href?: T;
        icon?: T;
        target?: T;
        id?: T;
      };
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogLatestPostsBlock_select".
 */
export interface BlogLatestPostsBlockSelect<T extends boolean = true> {
  title?: T;
  information?: T;
  count?: T;
  linkText?: T;
  linkUrl?: T;
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NoteBlock_select".
 */
export interface NoteBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  tagline?: T;
  title?: T;
  subtitle?: T;
  form?: T;
  anchorId?: T;
  isDark?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  excerpt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?: {
    links?:
      | {
          text: string;
          href?: string | null;
          submenu?:
            | {
                text?: string | null;
                href?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    actions?:
      | {
          variant?: ('primary' | 'secondary' | 'tertiary' | 'link') | null;
          text: string;
          href: string;
          /**
           * astro-icon name, e.g. tabler:rocket
           */
          icon?: string | null;
          target?: ('_self' | '_blank') | null;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    columns?:
      | {
          title?: string | null;
          links?:
            | {
                text?: string | null;
                href?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    socialLinks?:
      | {
          label?: string | null;
          /**
           * astro-icon name
           */
          icon?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    note?: string | null;
    legalLinks?:
      | {
          text?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  defaultSeo?: {
    metaTitle?: string | null;
    /**
     * e.g. %s — My Site
     */
    titleTemplate?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  analytics?: {
    googleAnalyticsId?: string | null;
  };
  theme?: {
    mode?: ('light' | 'dark' | 'system') | null;
    /**
     * Primary brand colour, hex e.g. #7a8b3a
     */
    accentColor?: string | null;
    /**
     * CSS font-family stack for headings (optional)
     */
    headingFont?: string | null;
    /**
     * CSS font-family stack for body text (optional)
     */
    bodyFont?: string | null;
    /**
     * Global corner radius scale
     */
    radius?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        links?:
          | T
          | {
              text?: T;
              href?: T;
              submenu?:
                | T
                | {
                    text?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        actions?:
          | T
          | {
              variant?: T;
              text?: T;
              href?: T;
              icon?: T;
              target?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    text?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        socialLinks?:
          | T
          | {
              label?: T;
              icon?: T;
              href?: T;
              id?: T;
            };
        note?: T;
        legalLinks?:
          | T
          | {
              text?: T;
              href?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        titleTemplate?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
      };
  theme?:
    | T
    | {
        mode?: T;
        accentColor?: T;
        headingFont?: T;
        bodyFont?: T;
        radius?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}